=== seriouslysean/katiecrafts/.astro/collections/posts.schema.json
{
  "$ref": "#/definitions/posts",
  "definitions": {
    "posts": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "publishedDate": {
          "type": "string"
        },
        "excerpt": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "featuredImage": {
          "type": "object",
          "properties": {
            "src": {
              "type": "string"
            },
            "width": {
              "type": "number"
            },
            "height": {
              "type": "number"
            },
            "alt": {
              "type": "string"
            }
          },
          "required": [
            "src"
          ],
          "additionalProperties": false
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "slug": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "slug"
            ],
            "additionalProperties": false
          },
          "default": []
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/posts/properties/categories/items"
          },
          "default": []
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "slug",
        "date",
        "publishedDate",
        "content"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== seriouslysean/katiecrafts/data/posts/amigurumi-lemon-and-lime/post.json
{
  "title": "Amigurumi Lemon and Lime",
  "slug": "amigurumi-lemon-and-lime",
  "date": "20150814",
  "publishedDate": "2015-08-14",
  "excerpt": "<p>My crocheted fruit filled bowl is getting crowded slowly but surely! The bowl is now brimming with cherries, a pear, an orange, a lemon and a lime! (Next up: a plum and a banana!) Learn how to make the happy little lemon and lime right here!</p>\n",
  "content": "<p>My crocheted fruit filled bowl is getting crowded slowly but surely! The bowl is now brimming with <strong><a href=\"/amigurumi-cherries-pattern/\">cherries</a></strong>, a pear, an orange, a lemon and a lime! (Next up: a plum and a banana!) Learn how to make the happy little lemon and lime right here!</p>\n<p>Crafter June Gilbank has a wonderful blog called <a href=\"http://www.planetjune.com/blog/\" target=\"_blank\" rel=\"noopener noreferrer\">Planet June</a> where she offers some free crochet patterns, including several amigurumi citrus patterns! I used June’s lemon and lime patterns as the basis for my cute little smiling citrus, with a few tweaks. Please make sure you <a href=\"http://www.planetjune.com/blog/free-crochet-patterns/amigurumi-citrus-collection/\" target=\"_blank\" rel=\"noopener noreferrer\">head over to her site to her original patterns</a>, because they are just wonderful! As I was using a different yarn and hook and wanted the lemon a little larger, I had to make a couple changes to mine, which are listed below.</p>\n<h2>Lemon</h2>\n<h3>Materials:</h3>\n<ul>\n<li>Yellow worsted weight yarn</li>\n<li>Lime green worsted weight yarn</li>\n<li>G6 crochet hook</li>\n<li>Stuffing/polyfill</li>\n<li>2 Solid black safety eyes, 6mm (with backs)</li>\n<li>Embroidery floss, black</li>\n<li>Embroidery needle</li>\n<li>Yarn needle</li>\n<li>Stitch marker</li>\n</ul>\n<h3>Pattern Notes:</h3>\n<p>dec = decrease</p>\n<p>inc = increase</p>\n<p>sc = single crochet</p>\n<p>st = stitch</p>\n<h3>Instructions:</h3>\n<p>Start with green yarn.</p>\n<ul>\n<li>Round 1: 4 sc into a ring, change to yellow yarn.</li>\n<li>Round 2: (inc in next st, sc in next st) 2x – (6)</li>\n<li>Round 3: (inc in next st, sc in next st) 3x – (9)</li>\n<li>Round 4: (sc in next st, inc in next st, sc in next st) 3x – (12)</li>\n<li>Round 5: (inc in next st, sc in next st) 6x – (18)</li>\n<li>Round 6: (sc in next st, inc in next st, sc in next st) 6x – (24)</li>\n<li>Rounds 7 + 8: sc in each st around – (24)</li>\n<li>Round 9: (inc in next st, sc in next 3 st) 6x – (30)</li>\n<li>Rounds 10 – 14: sc in each st around – (30)</li>\n<li>Round 15: (dec, sc in next 3 st) 6x – (24)</li>\n<li>Rounds 16 + 17: sc in each st around – (24)</li>\n<li>Round 18: (sc in next st, dec, sc in next st) 6x – (18)</li>\n<li>Round 19: (dec, sc in next st) 6x – (12)</li>\n<li>Round 20: sc in each st around – (12)</li>\n<li><em>Take a break from crocheting for a moment. Decide where you want your eyes to be and follow instructions on safety eyes package to attach them. Then use embroidery floss and needle to stitch on a mouth. Make sure it’s secured so it cannot be pulled out. Then add your stuffing, shaping the lemon. Okay, continue crocheting now!</em></li>\n<li>Round 21: (dec, sc) 4x – (8)</li>\n<li>Round 22: dec til closed. Finished off. Weave in ends.</li>\n</ul>\n<h2>Lime</h2>\n<h3>Materials:</h3>\n<ul>\n<li>Lime green worsted weight yarn</li>\n<li>G6 crochet hook</li>\n<li>Stuffing/polyfill</li>\n<li>2 Solid black safety eyes, 6mm (with backs)</li>\n<li>Embroidery floss, black</li>\n<li>Embroidery needle</li>\n<li>Yarn needle</li>\n<li>Stitch marker</li>\n</ul>\n<h3>Pattern Notes:</h3>\n<p>dec = decrease</p>\n<p>inc = increase</p>\n<p>sc = single crochet</p>\n<p>st = stitch</p>\n<h3>Instructions:</h3>\n<ul>\n<li>Round 1: 4 sc into a ring</li>\n<li>Round 2: (inc in next st, sc in next st) 2x – (6)</li>\n<li>Round 3: inc in each st around – (12)</li>\n<li>Round 4: (inc in next st, sc in next st) 6x – (18)</li>\n<li>Round 5: (sc in next st, inc in next st, sc in next st) 6x – (24)</li>\n<li>Round 6: sc in each st around – (24)</li>\n<li>Round 7: (inc, sc in next 7 st) 3x – (27)</li>\n<li>Round 8 – 10: sc in each st around – (27)</li>\n<li>Round 11: (dec, sc in next 7 st) 3x – (24)</li>\n<li>Round 12: sc in each st around – (24)</li>\n<li>Round 13: (sc in next st, dec, sc in next st) 6x – (18)</li>\n<li>Round 14: (dec, sc in next st) 6x – (12)</li>\n<li>Round 15: dec til closed. Finished off. Weave in ends.</li>\n</ul>\n<p>I’m thinking of finishing off the bowl with a cute little heart shaped peach! What other fruits should I add? What other free amigurumi crochet patterns do you want to see?</p>\n",
  "featuredImage": {
    "src": "/posts/amigurumi-lemon-and-lime/featured.png",
    "width": 1280,
    "height": 1280,
    "alt": "Amigurumi Lemon & Lime Crochet Patterns on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 316,
      "name": "amigurumi",
      "slug": "amigurumi"
    },
    {
      "id": 31,
      "name": "crochet",
      "slug": "crochet"
    },
    {
      "id": 57,
      "name": "free pattern",
      "slug": "free-pattern"
    },
    {
      "id": 107,
      "name": "freebie friday",
      "slug": "freebie-friday"
    },
    {
      "id": 1440,
      "name": "fruit bowl",
      "slug": "fruit-bowl"
    },
    {
      "id": 342,
      "name": "lemon",
      "slug": "lemon"
    },
    {
      "id": 1439,
      "name": "lime",
      "slug": "lime"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/spring-flowers-nail-art/post.json
{
  "title": "Spring Flowers Nail Art",
  "slug": "spring-flowers-nail-art",
  "date": "20160404",
  "publishedDate": "2016-04-04",
  "excerpt": "<p>It’s April already! Wow! The year is flying by and the weather is changing every day. I saw tons of beautiful flowers and trees blooming all over this weekend so I figured I may as well try a new Spring Flowers nail art design for Manicure Monday! This one incorporates negative space, happy Spring colors, [&hellip;]</p>\n",
  "content": "<p>It’s April already! Wow! The year is flying by and the weather is changing every day. I saw tons of beautiful flowers and trees blooming all over this weekend so I figured I may as well try a new Spring Flowers nail art design for Manicure Monday! This one incorporates negative space, happy Spring colors, flowers and rhinestones for a really fun look.</p>\n<p>You can use whatever nail polish colors you prefer, but the below picks are the ones I liked for this tutorial.</p>\n<h2>Materials:</h2>\n<ul>\n<li>Yellow nail polish</li>\n<li>Pink nail polish</li>\n<li>Lavender nail polish</li>\n<li>Light blue nail polish</li>\n<li>Clear top coat</li>\n<li>Dotting tool</li>\n<li>Acrylic nail art rhinestones</li>\n</ul>\n<h2>Instructions:</h2>\n<ul>\n<li>Begin with clean, dry nails. Pick which you’d like to do flowers on and which you’d like solid. Since I was using four different colors, I decided to do one solid nail of each color and the other six would be floral.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1798-1.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1799-2.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>Use the large end of the dotting tool dipped in your first color, and make 3 to 5 dots in a circle to create a flower. Do this in random spots on each of the nails you’ve designated as “flower nails.” Let dry in between layers.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1800-3.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1801-4.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>Clean off your dotting tool and repeat this process with the other three colors, one at a time. Be sure to flip your dotting tool over and use the smaller end to make tinier flowers, too!</li>\n<li>While your flowers finish drying, do one coat of each solid on your remaining nails. Let dry completely, and do a second coat. Let dry.</li>\n<li>When ALL your nails are COMPLETELY dry (not even tacky!), you may seal in your look with clear polish. If they are still slightly damp, the flower colors will streak into each other and ruin your design!</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1802-5.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1805-6.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1803-7.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1804-8.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>With the clear polish still wet, carefully place a nail gem in the center of a few select flowers on each nail. If you have quick drying top coat, make sure you only paint one nail at a time to assure the polish is still wet enough to hold the rhinestone.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1806-9.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/spring-flowers-nail-art/img-1807-10.jpg\" alt=\"Spring Flowers Nail Art Tutorial by Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>Let your nails dry and then clean up any stray polish from your skin.</li>\n<li>You’re all done! Happy Spring!</li>\n</ul>\n<p>What other Spring nail art tutorials would you like to see? Comment below and I’ll try a new one soon!</p>\n",
  "featuredImage": {
    "src": "/posts/spring-flowers-nail-art/featured.jpg",
    "width": 1326,
    "height": 1326,
    "alt": "Spring Flowers Nail Art Tutorial by Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 983,
      "name": "floral",
      "slug": "floral"
    },
    {
      "id": 127,
      "name": "flowers",
      "slug": "flowers"
    },
    {
      "id": 384,
      "name": "manicure monday",
      "slug": "manicure-monday"
    },
    {
      "id": 40,
      "name": "nail art",
      "slug": "nail-art"
    },
    {
      "id": 219,
      "name": "nail design",
      "slug": "nail-design"
    },
    {
      "id": 1339,
      "name": "negative space",
      "slug": "negative-space"
    },
    {
      "id": 329,
      "name": "spring",
      "slug": "spring"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/words-for-wednesday-dare/post.json
{
  "title": "Words for Wednesday: Dare",
  "slug": "words-for-wednesday-dare",
  "date": "20150819",
  "publishedDate": "2015-08-19",
  "excerpt": "<p><p>Happy Wednesday! Today’s wonderful quote is one from the dreamer himself, Walt Disney. “First, Think. Second, Believe. Third, Dream. & Finally, Dare.”</p></p>",
  "content": "<p><br></p><p>Happy Wednesday! Today’s wonderful quote is one from the dreamer himself, Walt Disney.</p><blockquote><p><i><b>“First, Think.</b></i></p><p><i><b>Second, Believe.</b></i></p><p><i><b>Third, Dream.</b></i></p><p><i><b>&#x26; Finally, Dare.”</b></i></p></blockquote><p>Today I am spending the day with my dear friend and her babes at the Philly Zoo- yay! The zoo is where my Husband and I first met (okay, we met on the journey to the zoo but didn’t actually speak until we were there!) and I haven’t been back in years so I’m excited to go. It will also be fun to go with a little kid who will find wonder in it! I hope whatever your day holds, you remember Disney’s words!</p><p>Share your Words for Wednesday below!</p>",
  "featuredImage": {
    "src": "/posts/words-for-wednesday-dare/featured.jpg",
    "width": 1024,
    "height": 1024
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 1020,
      "name": "quote",
      "slug": "quote"
    },
    {
      "id": 1066,
      "name": "walt disney",
      "slug": "walt-disney"
    },
    {
      "id": 1068,
      "name": "words for wednesday",
      "slug": "words-for-wednesday"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/words-for-wednesday-smile/post.json
{
  "title": "Words For Wednesday: Smile",
  "slug": "words-for-wednesday-smile",
  "date": "20150624",
  "publishedDate": "2015-06-24",
  "excerpt": "<p><p>Words For Wednesday: Smile “Be Happy And Smile!” Sometimes it’s as easy as that! It may be a hard thing to do, but simply smiling can improve your mood.</p></p>",
  "content": "<p>Words For Wednesday: Smile</p><p><em>“Be Happy And Smile!”</em></p><p>Sometimes it’s as easy as that! It may be a hard thing to do, but simply smiling can improve your mood.</p><p>No matter what you’re doing right now, stop and smile! And have a great (happy) Wednesday! 🙂</p>",
  "featuredImage": {
    "src": "/posts/words-for-wednesday-smile/featured.jpg",
    "width": 1024,
    "height": 1024,
    "alt": "Words For Wednesday: Smile on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 1384,
      "name": "happy",
      "slug": "happy"
    },
    {
      "id": 1343,
      "name": "qotd",
      "slug": "qotd"
    },
    {
      "id": 1020,
      "name": "quote",
      "slug": "quote"
    },
    {
      "id": 1383,
      "name": "smile",
      "slug": "smile"
    },
    {
      "id": 1068,
      "name": "words for wednesday",
      "slug": "words-for-wednesday"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/my-etsy-picks-back-school-guide/post.json
{
  "title": "My Etsy Picks: Back to School Guide",
  "slug": "my-etsy-picks-back-school-guide",
  "date": "20140804",
  "publishedDate": "2014-08-04",
  "excerpt": "<p><p>My Etsy Picks: Back to School Guide Hello, Monday! If you are an avid Katie Crafts reader, you may have noticed that there was no Sunday Funday post yesterday. For the moment, weekend posts (unless it’s something great that I *need* to share *immediately*… like a cat photo) will be on hiatus. I love having […]</p></p>",
  "content": "<p>My Etsy Picks: Back to School Guide</p><p>Hello, Monday! If you are an avid Katie Crafts reader, you may have noticed that there was no Sunday Funday post yesterday. For the moment, weekend posts (unless it’s something great that I *need* to share *immediately*… like a cat photo) will be on hiatus. I love having daily things to share with you guys, but with all the other obligations in my life, and with the beautiful summer days coming to an end soon, I need my weekends to myself! Don’t fret, though! You’ll still see me Monday through Friday, with great posts like the one I have for today: an</p><strong><p>Etsy Back to School Guide</p></strong><p>that you will certainly love!</p><p>It feels like just yesterday I was blogging about</p><a title=\"Grad Gifts: My Etsy Picks\" href=\"/grad-gifts-my-etsy-picks/\">gifts to give the graduates</a><p>in your life, and here we are just a few weeks from starting school up again! Back-to-school shopping with my mom was always my favorite. The art supplies, the colorful notebooks and fun pens, the organizational 5 pocketed binders. . . my Mom loved back to school shopping for me as much as I liked picking it all out. I rarely complained that the summer was ending, because it meant soon I’d get to use my brand new</p><a title=\"Lisa Frank Folders on Amazon\" href=\"http://amzn.to/1s2J48m\" target=\"_blank\" rel=\"noopener noreferrer\">Lisa Frank</a><p>folders! I look forward to the day I get to go back to school shopping with my future kids. I can only hope they enjoy it the way I always did!</p><p>If you are looking for some outside-the-box school supplies, Etsy artists have you covered! Above is a treasury I put together of some really great items for your kids (young and old) so they can start the school year off right! And since it’s only the beginning of August, you have time to order these gifts for them so they can proudly present them their first day back! You can find each of the shops from this treasury listed below. Happy shopping!</p><p>Check out the</p><em><a title=\"Back To School Gift Guide on Etsy\" href=\"https://www.etsy.com/treasury/MTAzNjM3NjF8MjcyNDAyOTAzMQ/back-to-school-guide\" target=\"_blank\" rel=\"noopener noreferrer\">full treasury right here,</a></em><p>and give it a heart if you deem it worthy!</p><ol><li><a title=\"Blessed Type on Etsy\" href=\"https://www.etsy.com/listing/196331927/dorm-decor-college-dorm-decorations-dorm\" target=\"_blank\" rel=\"noopener noreferrer\">Blessed Type</a></li><li><a title=\"Thai Handbags on Etsy\" href=\"https://www.etsy.com/listing/162564051/orange-small-backpack-book-bag-handmade\" target=\"_blank\" rel=\"noopener noreferrer\">Thai Handbags</a></li><li><a title=\"Little Maisie on Etsy\" href=\"https://www.etsy.com/listing/193832082/handwriting-alphabet-back-to-school\" target=\"_blank\" rel=\"noopener noreferrer\">Little Maisie</a></li><li><a title=\"GET Good on Etsy\" href=\"https://www.etsy.com/listing/198172408/multi-colored-zippered-pencil-case-back\" target=\"_blank\" rel=\"noopener noreferrer\">GET Good</a></li><li><a title=\"Brown Cow Creatives on Etsy\" href=\"https://www.etsy.com/listing/158078404/back-to-school-clipart-backgrounds\" target=\"_blank\" rel=\"noopener noreferrer\">Brown Cow Creatives</a></li><li><a title=\"Boutique Sew Unique on Etsy\" href=\"https://www.etsy.com/listing/157177311/first-day-of-kindergarten-tshirt-back-to\" target=\"_blank\" rel=\"noopener noreferrer\">Boutique Sew Unique</a></li><li><a title=\"Dixie Sisters on Etsy\" href=\"https://www.etsy.com/listing/189325012/back-to-school-sticky-note-pad-holder\" target=\"_blank\" rel=\"noopener noreferrer\">Dixie Sisters</a></li><li><a title=\"When It Rains Shop on Etsy\" href=\"https://www.etsy.com/listing/157177311/first-day-of-kindergarten-tshirt-back-to\" target=\"_blank\" rel=\"noopener noreferrer\">When It Rains Shop</a></li><li><a title=\"Musu Store on Etsy\" href=\"https://www.etsy.com/listing/128353241/owl-laptop-case-laptop-bag-laptop-sleeve\" target=\"_blank\" rel=\"noopener noreferrer\">Musu Store</a></li><li><a title=\"Happy Thoughts Gifts on Etsy\" href=\"https://www.etsy.com/listing/160468174/personalized-pencil-crayon-box-art\" target=\"_blank\" rel=\"noopener noreferrer\">Happy Thoughts Gifts</a></li><li><a title=\"Dorm Desk Pockets on Etsy\" href=\"https://www.etsy.com/listing/192679837/the-aussie-pouch-dorm-chair-dorm-desk\" target=\"_blank\" rel=\"noopener noreferrer\">Dorm Desk Pockets</a></li><li><a title=\"Delighted Designs Vinyl on Etsy\" href=\"https://www.etsy.com/listing/158112878/first-last-day-of-school-chalkboard-sign\" target=\"_blank\" rel=\"noopener noreferrer\">Delighted Designs Vinyl</a></li><li><a title=\"Luv Ur Locker on Etsy\" href=\"https://www.etsy.com/listing/155145033/purple-white-polka-dot-locker-wallpaper\" target=\"_blank\" rel=\"noopener noreferrer\">Luv Ur Locker</a></li><li><a title=\"Urban Creative on Etsy\" href=\"https://www.etsy.com/listing/159434858/lime-green-chevron-laundry-bag-and\" target=\"_blank\" rel=\"noopener noreferrer\">Urban Creative</a></li><li><a title=\"Mad For Monograms on Etsy\" href=\"https://www.etsy.com/listing/123645156/personalized-dry-erase-board\" target=\"_blank\" rel=\"noopener noreferrer\">Mad For Monograms</a></li><li><a title=\"Paper Doll Printing on Etsy\" href=\"https://www.etsy.com/listing/153584661/personalized-custom-notepads-from-the\" target=\"_blank\" rel=\"noopener noreferrer\">Paper Doll Printing</a></li></ol><p>Which back to school item do you like the best? Share in the comments!</p>",
  "featuredImage": {
    "src": "/posts/my-etsy-picks-back-school-guide/featured.jpg",
    "width": 663,
    "height": 250,
    "alt": "My Etsy Picks: Back to School Guide on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 957,
      "name": "back to school",
      "slug": "back-to-school"
    },
    {
      "id": 816,
      "name": "college",
      "slug": "college"
    },
    {
      "id": 808,
      "name": "dorm room",
      "slug": "dorm-room"
    },
    {
      "id": 82,
      "name": "etsy",
      "slug": "etsy"
    },
    {
      "id": 956,
      "name": "gift guide",
      "slug": "gift-guide"
    },
    {
      "id": 961,
      "name": "grade school",
      "slug": "grade-school"
    },
    {
      "id": 815,
      "name": "high school",
      "slug": "high-school"
    },
    {
      "id": 960,
      "name": "my etsy picks",
      "slug": "my-etsy-picks"
    },
    {
      "id": 958,
      "name": "school shopping",
      "slug": "school-shopping"
    },
    {
      "id": 959,
      "name": "supplies",
      "slug": "supplies"
    },
    {
      "id": 758,
      "name": "treasury",
      "slug": "treasury"
    }
  ]
}
