=== seriouslysean/katiecrafts/.astro/collections/posts.schema.json
{
  "$ref": "#/definitions/posts",
  "definitions": {
    "posts": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "publishedDate": {
          "type": "string"
        },
        "excerpt": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "featuredImage": {
          "type": "object",
          "properties": {
            "src": {
              "type": "string"
            },
            "width": {
              "type": "number"
            },
            "height": {
              "type": "number"
            },
            "alt": {
              "type": "string"
            }
          },
          "required": [
            "src"
          ],
          "additionalProperties": false
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "slug": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "slug"
            ],
            "additionalProperties": false
          },
          "default": []
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/posts/properties/categories/items"
          },
          "default": []
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "slug",
        "date",
        "publishedDate",
        "content"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== seriouslysean/katiecrafts/data/posts/nail-art-stamping/post.json
{
  "title": "Nail Art Stamping",
  "slug": "nail-art-stamping",
  "date": "20160229",
  "publishedDate": "2016-02-29",
  "excerpt": "<p>A few years ago, Husband bought me a stamping kit to further my nail art obsession. I tried it a few times and did not have much luck. Next week we are going to the 2016 Philadelphia Flower Show (my favorite day of the year!) and I want to have some super cute floral stamped [&hellip;]</p>\n",
  "content": "<p>A few years ago, Husband bought me a stamping kit to further my nail art obsession. I tried it a few times and did not have much luck. Next week we are going to the <strong>2016 <a href=\"/philly-flower-show-2015-recap/\">Philadelphia Flower Show</a></strong> (my favorite day of the year!) and I want to have some super cute floral stamped nails for the occasion. I decided I should test out the nail art stamping technique once again!</p>\n<p>I’m glad I did because I could clearly see which colors worked together and which did not! I like that each nail has it’s own unique design but they are very dark. For the Flower Show next week, I’ll do a light base coat with darker stamps instead! I’ll be sure to share how that one turns out on my <strong><a href=\"https://www.instagram.com/imkatiecrafts/\" target=\"_blank\" rel=\"noopener noreferrer\">Instagram Page!</a></strong></p>\n<h2>Materials:</h2>\n<ul>\n<li>Stamping kit</li>\n<li>Nail polish in various shades</li>\n<li>Clear top coat</li>\n<li>Scraper tool (my kit came with one, but I lost it somewhere along the way… which is why I used some of my business cards to do the job!)</li>\n</ul>\n<h2>Instructions:</h2>\n<ul>\n<li>You’ll need your base coat already on your nails and completely dried!! I did mine in dark purple the evening before I stamped, to ensure by the next day they were 110% ready to go.</li>\n<li>Pick your design and place disc in holder.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0936-1.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0937-2.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>Dab the nail polish shade of your choosing on top of the design and immediately scrape away the excess with your tool/business card. Don’t scrape TOO hard, or you’ll remove some of the polish from inside the design.</li>\n<li>Press with the stamper tool in a rocking (side to side) motion, never lifting the stamper up. Be sure to apply even pressure. When you think you’ve captured the whole design, lift.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0938-3.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0939-4.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>The stamp should have lifted from the disc and now be on your stamper, staring at you! Pick which nail you want to transfer it to and use the same rocking motion to transfer it on to your nail.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0940-5.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0943-6.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>Repeat steps with however many stamp designs and colors you like! After a few uses, the design with become gummy and you won’t get a clean stamp out of it. You can clean it out with nail polish remover and a q-tip if you want to continue using that design- but remember, you run the risk of nail polish remover touching your nails and ruining what you’ve already done! This is why I had several designs in different colors picked out to combine together.</li>\n</ul>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/nail-art-stamping/img-0945-7.jpg\" alt=\"Nail Art Stamping on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<ul>\n<li>When dry, add a clear top coat to lock in look. Clean up polish from skin and you’re all done!</li>\n</ul>\n<p>Not all DIYs turn out well, and this is the case for today’s manicure! However, if I didn’t try it out the way I did, I wouldn’t have known what to do for next time. I hope my nails for the Flower Show turn out way better!!</p>\n<p>If you have had luck with the stamping technique, share your photos below!</p>\n",
  "featuredImage": {
    "src": "/posts/nail-art-stamping/featured.jpg",
    "width": 1326,
    "height": 1326,
    "alt": "Nail Art Stamping on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 10,
      "name": "Beauty",
      "slug": "beauty"
    }
  ],
  "tags": [
    {
      "id": 74,
      "name": "beauty",
      "slug": "beauty"
    },
    {
      "id": 384,
      "name": "manicure monday",
      "slug": "manicure-monday"
    },
    {
      "id": 40,
      "name": "nail art",
      "slug": "nail-art"
    },
    {
      "id": 219,
      "name": "nail design",
      "slug": "nail-design"
    },
    {
      "id": 39,
      "name": "nail polish",
      "slug": "nail-polish"
    },
    {
      "id": 202,
      "name": "philadelphia flower show",
      "slug": "philadelphia-flower-show"
    },
    {
      "id": 415,
      "name": "stamping",
      "slug": "stamping"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/motivation-monday-believe-2/post.json
{
  "title": "Motivation Monday: Believe",
  "slug": "motivation-monday-believe-2",
  "date": "20150803",
  "publishedDate": "2015-08-03",
  "excerpt": "<p>I had a very lovely and relaxing weekend, though I didn’t get done a fraction of what I wanted to. That is why I thought it would be a good time for a Motivation Monday quote! This one comes from T. Roosevelt. </p>\n",
  "content": "<p>I had a very lovely and relaxing weekend, though I didn’t get done a fraction of what I wanted to. That is why I thought it would be a good time for a Motivation Monday quote! This one comes from T. Roosevelt. </p>\n<blockquote><p><em><strong>“Believe you can & you’re halfway there.”</strong></em><em><strong> </strong></em></p></blockquote>\n<p>The photo behind the quote is one I took yesterday when I was visiting <strong><a href=\"/shofuso-japanese-house-and-garden/\">Shofuso Japanese Gardens</a></strong>. You may have already seen the original on <strong><a href=\"https://instagram.com/p/548MsHM7nO/?taken-by=imkatiecrafts\" target=\"_blank\" rel=\"noopener noreferrer\">Instagram</a></strong>, but I thought it was a pretty great pic to use for this quote! What do you think? I can’t wait to go back again in the Fall when some of the trees are changing. I’ll be sure to bring my fancy camera with me on that trip!</p>\n<p>Hope you have a great Monday! Share any motivational quotes you like below!</p>\n",
  "featuredImage": {
    "src": "/posts/motivation-monday-believe-2/featured.jpg",
    "width": 2448,
    "height": 2448,
    "alt": "Motivation Monday: Believe on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 1426,
      "name": "believe",
      "slug": "believe"
    },
    {
      "id": 1372,
      "name": "motivation monday",
      "slug": "motivation-monday"
    },
    {
      "id": 1425,
      "name": "roosevelt",
      "slug": "roosevelt"
    },
    {
      "id": 1332,
      "name": "shofuso japanese house and garden",
      "slug": "shofuso-japanese-house-and-garden"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/meet-oliver/post.json
{
  "title": "Meet Oliver!",
  "slug": "meet-oliver",
  "date": "20140611",
  "publishedDate": "2014-06-11",
  "excerpt": "<p>There is no featured Etsy shop for today, so no real post to share. Instead, enjoy meeting my friend’s new puppy, Oliver! Isn’t he adorable!?</p>\n",
  "content": "<p>There is no featured Etsy shop for today, so no real post to share. Instead, enjoy meeting my friend’s new puppy, Oliver! Isn’t he adorable!?</p>\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/meet-oliver/img-3772-1.jpg\" alt=\"Meet Oliver! on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/meet-oliver/img-3765-2.jpg\" alt=\"Meet Oliver! on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/meet-oliver/img-3773-3.jpg\" alt=\"Meet Oliver! on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/meet-oliver/img-3780-4.jpg\" alt=\"Meet Oliver! on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n",
  "featuredImage": {
    "src": "/posts/meet-oliver/featured.jpg",
    "width": 1280,
    "height": 1706,
    "alt": "Meet Oliver! on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 761,
      "name": "dog",
      "slug": "dog"
    },
    {
      "id": 762,
      "name": "oliver",
      "slug": "oliver"
    },
    {
      "id": 760,
      "name": "puppy",
      "slug": "puppy"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/diy-glitter-mug/post.json
{
  "title": "DIY Glitter Mug Tutorial",
  "slug": "diy-glitter-mug",
  "date": "20160317",
  "publishedDate": "2016-03-17",
  "excerpt": "<p><p>Glitter may be the “herpes” of the craft world, but I love it just the same! I’ve been glittering everything lately, and thought I would show you guys how to do it as well. You can do ANY shape you like, or even your initial if you prefer. I have several mugs with “K” already on […]</p></p>",
  "content": "<p>Glitter may be the “herpes” of the craft world, but I love it just the same! I’ve been glittering everything lately, and thought I would show you guys how to do it as well. You can do ANY shape you like, or even your initial if you prefer. I have several mugs with “K” already on them, so I decided I’d do something to celebrate today, St. Patrick’s Day: a 4 leaf clover! Let’s whip out the</p><strong><a href=\"/how-to-make-an-adhesive-stencil-two-ways/\">stencil we made yesterday</a></strong><p>and get to work!</p><p>Just because I made a shamrock for my mug, doesn’t make this a St. Paddy’s Day craft exclusively- as I said you can do anything your heart desires! You can even glitter just the bottom half of the mug instead of a shape if you like. Tips for that are at the bottom of the page.</p><h2>Materials:</h2><ul><li><p>Adhesive stencil*</p></li><li><p>Glitter in your choice of color (I used</p><strong><a href=\"http://amzn.to/1T8BOch\" target=\"_blank\" rel=\"nofollow noopener noreferrer\">Martha Stewart’s Iridescent Glitter</a></strong><p>again!)</p></li><li><p>Mod Podge, Gloss</p></li><li><p>Ceramic mug</p></li><li><p>Dry paint brush</p></li><li><p>Foam brush</p></li><li><p>Paper</p></li></ul><p>*</p><em><p>Make your own adhesive stencil by hand</p></em><p>or</p><em><p>use your Silhouette Cameo machine to craft one</p></em><p>!</p><strong><a href=\"/how-to-make-an-adhesive-stencil-two-ways/\">Click here to learn how to make an adhesive stencil by hand or with your Cameo!</a></strong><h2>Instructions:</h2><ul><li><p>Pick where on your mug you would like the image to be. Take into account whether you are right- or left-handed. When you bring the mug up to your mouth, only one side of the mug shows (while the other is hidden). You want the design to be on the correct side so everyone around you can enjoy the cuteness too!</p></li></ul><ul><li><em><p>Slowly</p></em><p>and</p><em><p>gently</p></em><p>place your adhesive stencil down on your mug. You may need to pull it up and re-lay it a couple of times to get it perfect. That’s why contact paper stencils are so great! They aren’t going to permanently stick to your mug instantly thus they give you the flexibility to shift things if needed.</p></li><li><p>Be sure all the inside parts of the stencil are totally flat and adhered to the mug.</p></li><li><p>Fold your paper in half and create a crease, then unfold it and lay it on your table in front of you. You’ll be using this as your workspace.</p></li></ul><ul><li><p>Use a thin coat of Mod Podge on your foam brush to completely cover the inside of the stencil- in my case, the shamrock. On places that are thinner cuts that may want to come up (like the inside slivers of the clover leaves), sweep the Mod Podge on from the outside towards the inside. If you go from the inside to the outside, your brush may pull up the stencil.</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0977.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><ul><li><p>Tap the glitter all over your Mod Podge’d area until it is completely covered. Be sure to do so over the paper so you don’t make a mess!</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0978.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><ul><li><p>Let the mug sit and dry for an hour.</p></li><li><p>Use a dry paintbrush to gently brush off any excess glitter from the design. Be sure to go over the middle of the design as well, to get rid of loose glitter.</p></li><li><p>Repeat the Mod Podge/Glitter steps a second time if there are spots showing through without glitter.</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0980.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><ul><li><p>Remove stencil and let mug dry for an hour.</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0988.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><ul><li><p>Use dry paintbrush to again brush off excess glitter. Use your fingernail to scrape off any parts that bother you and make it look pretty!</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0992.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><ul><li><p>Dab some Mod Podge on your foam brush and go over the image one last time, this time to seal the glitter in.</p></li><li><p>Replace excess glitter back in it’s container using the folded piece of paper.</p></li><li><p>Let mug dry for a day before you use it!</p></li></ul><p><img class=\"size-full post__image\" src=\"/posts/diy-glitter-mug/img-0996.jpg\" alt=\"DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com\" width=\"980\" height=\"980\"></p><h2>Tips:</h2><ul><li><p>If you just want to glitter the bottom half of your mug, you’ll do almost all the same steps. There are only a couple changes:</p><ul><li><p>Instead of a using a contact paper stencil, you will just use electrical tape around the bottom of the mug to get a clean line. I balance a pencil on something the height I want the line and gently turn the mug, marking it all the way around. Then I tape right above that line all the way around to get it straight.</p></li><li><p>I also use a different sealant for those. I opt for Triple Thick rather than Mod Podge, as it gives it a glass-like feel so it’s not glittery/gritty feeling. You can do the same for today’s tutorial, but since your hands aren’t wrapped around the image you are doing it really isn’t necessary. Especially because I do 2 – 3 coats of Triple Thick (waiting 24 hours in between each) rather than just one layer of Mod Podge sealant like in this tutorial.</p></li></ul></li><li><p>Really want to try this tutorial but don’t want to ruin one of the pretty coffee mugs in your cabinet? I got this one for a dollar at Ikea! There are usually also really nice ones at your local Dollar store too! They do the job perfectly. The Dollar Tree is also where I buy my contact paper!</p></li><li><p>Don’t forget to</p><em><p>wash your foam brush</p></em><p>in between layers! It starts to dry pretty quickly and once it does, there is no bringing it back to life.</p></li><li><p>These mugs are</p><strong><p>HAND WASH ONLY</p></strong><p>!!!! Do not put in dishwasher, do not let soak in water. Simply hand wash the inside. The sealant on the outside will keep the glitter from falling all over the place, but if hot water is blasted on it or it’s soaked for a period of time, it will sadly come off. There IS a dishwasher safe version of Mod Podge that will hold up better, but it takes 28 days to cure before it can be used/washed. If you are that patient, that’s awesome! I am not. 😉</p></li></ul><p>What will you glitter on your mug?</p>",
  "featuredImage": {
    "src": "/posts/diy-glitter-mug/featured.jpg",
    "width": 1326,
    "height": 1326,
    "alt": "DIY Glitter Mug Tutorial on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 1589,
      "name": "affiliate links",
      "slug": "affiliate-links"
    },
    {
      "id": 1409,
      "name": "amazon affiliates",
      "slug": "amazon-affiliates"
    },
    {
      "id": 288,
      "name": "clover",
      "slug": "clover"
    },
    {
      "id": 72,
      "name": "crafts",
      "slug": "crafts-2"
    },
    {
      "id": 185,
      "name": "diy",
      "slug": "diy"
    },
    {
      "id": 78,
      "name": "glitter",
      "slug": "glitter"
    },
    {
      "id": 198,
      "name": "how to",
      "slug": "how-to"
    },
    {
      "id": 1661,
      "name": "martha stewart glitter",
      "slug": "martha-stewart-glitter"
    },
    {
      "id": 1655,
      "name": "mug",
      "slug": "mug"
    },
    {
      "id": 287,
      "name": "shamrock",
      "slug": "shamrock"
    },
    {
      "id": 1240,
      "name": "st. patricks day",
      "slug": "st-patricks-day"
    },
    {
      "id": 1662,
      "name": "stencil",
      "slug": "stencil"
    },
    {
      "id": 187,
      "name": "tutorial",
      "slug": "tutorial"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/mabel-faceplanting/post.json
{
  "title": "",
  "slug": "mabel-faceplanting",
  "date": "20140810",
  "publishedDate": "2014-08-10",
  "excerpt": "\n",
  "content": "\n<div class=\"post__gallery\"><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/mabel-faceplanting/img-3437-1.jpg\" alt=\"Mabel Faceplant on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/mabel-faceplanting/img-3436-2.jpg\" alt=\"Mabel Faceplant on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div><div class=\"post__gallery-item\">\n          <img class=\"post__gallery-image post__image\" src=\"/posts/mabel-faceplanting/img-3434-3.jpg\" alt=\"Mabel Faceplant on Katie Crafts; https://www.katiecrafts.com\" width=\"600\" height=\"400\" loading=\"lazy\" decoding=\"async\">\n        </div>\n\t\t</div>\n\n",
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 975,
      "name": "faceplant",
      "slug": "faceplant"
    },
    {
      "id": 370,
      "name": "kitty",
      "slug": "kitty"
    },
    {
      "id": 37,
      "name": "loves cats",
      "slug": "loves-cats-2"
    },
    {
      "id": 19,
      "name": "mabel",
      "slug": "mabel"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/all-moved-in/post.json
{
  "title": "All Moved In!",
  "slug": "all-moved-in",
  "date": "20140923",
  "publishedDate": "2014-09-23",
  "excerpt": "<p><p>All our stuff is officially moved in, and we handed in our keys to our old apartment with a half hour to spare on Saturday night. Lucky is loving the new house, but Mabel- not so much!</p></p>",
  "content": "<p>All our stuff is officially moved in, and we handed in our keys to our old apartment with a half hour to spare on Saturday night. Lucky is loving the new house, but Mabel- not so much!</p><p>Lucky is finding all the sunspots, intently watching birds outside the window and taking the stairs by storm hopping up three at a time. Such a brave little adventurer. Mabel, on the other hand, is terrified. It takes her 10 minutes and a lot of coaxing to get her to go down one flight- and there are three total! She’s hiding under every box and in every crevice she can find and is barely eating (which is her favorite activity) but there have been a couple times she looked a little at ease, and we managed to snap pics of them!</p><p>Lucky, sprawled out on his new fave blanket.\n Mabel found a sun spot!</p><p>I hope they both settle in soon. I know I won’t until all the unpacking is done- which probably won’t be til next year! Anyone want to help?? 😉</p>",
  "featuredImage": {
    "src": "/posts/all-moved-in/featured.png",
    "width": 663,
    "height": 250,
    "alt": "All Moved In! on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 20,
      "name": "cats",
      "slug": "cats"
    },
    {
      "id": 370,
      "name": "kitty",
      "slug": "kitty"
    },
    {
      "id": 46,
      "name": "lucky",
      "slug": "lucky"
    },
    {
      "id": 19,
      "name": "mabel",
      "slug": "mabel"
    },
    {
      "id": 1002,
      "name": "moving",
      "slug": "moving"
    },
    {
      "id": 1059,
      "name": "new house",
      "slug": "new-house"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/lucky-and-mabel-as-baby/post.json
{
  "title": "",
  "slug": "lucky-and-mabel-as-baby",
  "date": "20140517",
  "publishedDate": "2014-05-17",
  "excerpt": "<p>How cute was the little Peanut when she was a kit? Her little ‘cone’ had to stay on for two weeks after her surgery and was bigger than she was. Loved the photos from it!</p>\n",
  "content": "<p><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-2527\" src=\"https://i0.wp.com/www.katiecrafts.com/wp-content/uploads/2014/05/IMG_3817-663x495.jpg?resize=663%2C495&ssl=1\" alt=\"Lucky and Mabel as Baby on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"495\" data-recalc-dims=\"1\" ></p>\n<p style=\"text-align: center;\">How cute was the little Peanut when she was a kit? Her little ‘cone’ had to stay on for two weeks after her surgery and was bigger than she was. Loved the photos from it!</p>\n",
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 370,
      "name": "kitty",
      "slug": "kitty"
    },
    {
      "id": 37,
      "name": "loves cats",
      "slug": "loves-cats-2"
    },
    {
      "id": 46,
      "name": "lucky",
      "slug": "lucky"
    },
    {
      "id": 19,
      "name": "mabel",
      "slug": "mabel"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/wordless-wednesday-so-long-sweet-summer/post.json
{
  "title": "Wordless Wednesday: So Long Sweet Summer",
  "slug": "wordless-wednesday-so-long-sweet-summer",
  "date": "20140910",
  "publishedDate": "2014-09-10",
  "excerpt": "<p>Wordless Wednesday: So Long Sweet Summer Doesn’t this photo say it all? Lucky enjoys a last shred of Summer: corn on the cob, freshly buttered and hand-served via his Papa.</p>\n",
  "content": "<p style=\"text-align: left\"><strong>Wordless Wednesday: So Long Sweet Summer</strong></p>\n<p style=\"text-align: left\">Doesn’t this photo say it all? Lucky enjoys a last shred of Summer: corn on the cob, freshly buttered and hand-served via his Papa.</p>\n<p style=\"text-align: left\">The end of Summer always makes me think of this Dashboard Confessional song:</p>\n<p style=\"text-align: left\"><em>So long sweet summer,</em><br>\n<em>I stumbled upon you and gratefully basked in your rays.</em><br>\n<em>So long sweet slumber.</em><br>\n<em>I fell into you now you’re gracefully falling away.</em></p>\n<p style=\"text-align: left\">Ahh, Dashboard. I think I’ll whip out my old albums and reminisce now.</p>\n<p style=\"text-align: left\">What ways will you enjoy your last bit of Summer? Are you happy or sad to see the heat leave and the brisk air roll in?</p>\n",
  "featuredImage": {
    "src": "/posts/wordless-wednesday-so-long-sweet-summer/featured.png",
    "width": 663,
    "height": 250,
    "alt": "Wordless Wednesday: So Long Sweet Summer on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 1047,
      "name": "corn",
      "slug": "corn"
    },
    {
      "id": 1049,
      "name": "dashboard confessional",
      "slug": "dashboard-confessional"
    },
    {
      "id": 46,
      "name": "lucky",
      "slug": "lucky"
    },
    {
      "id": 1048,
      "name": "so long sweet summer",
      "slug": "so-long-sweet-summer"
    },
    {
      "id": 856,
      "name": "summer",
      "slug": "summer"
    },
    {
      "id": 1050,
      "name": "wordless wednesday",
      "slug": "wordless-wednesday"
    }
  ]
}
