=== seriouslysean/katiecrafts/.astro/collections/posts.schema.json
{
  "$ref": "#/definitions/posts",
  "definitions": {
    "posts": {
      "type": "object",
      "properties": {
        "title": {
          "type": "string"
        },
        "slug": {
          "type": "string"
        },
        "date": {
          "type": "string"
        },
        "publishedDate": {
          "type": "string"
        },
        "excerpt": {
          "type": "string"
        },
        "content": {
          "type": "string"
        },
        "featuredImage": {
          "type": "object",
          "properties": {
            "src": {
              "type": "string"
            },
            "width": {
              "type": "number"
            },
            "height": {
              "type": "number"
            },
            "alt": {
              "type": "string"
            }
          },
          "required": [
            "src"
          ],
          "additionalProperties": false
        },
        "categories": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "type": "number"
              },
              "name": {
                "type": "string"
              },
              "slug": {
                "type": "string"
              }
            },
            "required": [
              "id",
              "name",
              "slug"
            ],
            "additionalProperties": false
          },
          "default": []
        },
        "tags": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/posts/properties/categories/items"
          },
          "default": []
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "title",
        "slug",
        "date",
        "publishedDate",
        "content"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== seriouslysean/katiecrafts/data/posts/happy-national-milk-chocolate-day/post.json
{
  "title": "Happy National Milk Chocolate Day!",
  "slug": "happy-national-milk-chocolate-day",
  "date": "20150728",
  "publishedDate": "2015-07-28",
  "excerpt": "<p>Yes, today is in fact National Milk Chocolate Day! Milk chocolate is one of life’s greatest gifts, so I plan on celebrating lots today!</p>\n",
  "content": "<p>Yes, today is in fact National Milk Chocolate Day! Milk chocolate is one of life’s greatest gifts, so I plan on celebrating lots today!</p>\n<p>Here is a little history about this wonderful treat. True milk chocolate was born in 1875, when Swiss chocolate manufacturer (and neighbor of Nestlé) Daniel Peter combined powdered milk with chocolate liquor. Peter was visiting Nestlé when he came up with the idea to combine their new invention of evaporated milk with chocolate. It was perfected even further a few years later when Lindt invented the conching machine, a mixer and agitator which would evenly distributes the cocoa butter in the chocolate, making it smoother.</p>\n<p>I love learning about chocolate almost as much as I like eating it! I hope you enjoy your National Milk Chocolate Day! Be sure to celebrate by having some chocolate today, and share your favorite chocolate related recipe in the comments for other readers to try!</p>\n",
  "featuredImage": {
    "src": "/posts/happy-national-milk-chocolate-day/featured.png",
    "width": 960,
    "height": 960,
    "alt": "Happy National Milk Chocolate Day! on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 104,
      "name": "chocolate",
      "slug": "chocolate"
    },
    {
      "id": 1416,
      "name": "national milk chocolate day",
      "slug": "national-milk-chocolate-day"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/wordless-wednesday-best-friends/post.json
{
  "title": "Wordless Wednesday: Best Friends",
  "slug": "wordless-wednesday-best-friends",
  "date": "20150204",
  "publishedDate": "2015-02-04",
  "excerpt": "<p>Wordless Wednesday: Best Friends If a picture is worth a thousand words, how many words is a four-in-one collage worth? This week, I must say “goodbye” see you soon to my best friend here in Philly, Tasha. She and her husband (and their adorable pup, Ollie) are moving a few hours away. I miss her [&hellip;]</p>\n",
  "content": "\n<p><strong>Wordless Wednesday: Best Friends</strong></p>\n<p>If a picture is worth a thousand words, how many words is a four-in-one collage worth? This week, I must say “<del>goodbye”</del> <em>see you soon</em> to my best friend here in Philly, Tasha. She and her husband (and their adorable pup, Ollie) are moving a few hours away. I miss her already.</p>\n<p>We were friendly for a couple years, and she was one of my favorite people to hang out with, but we became best friends right around the time I lost my mom. Setting bridal appointments and planning a wedding alone right after her death was really hard on me. Tasha offered to help and I took her up on it. We’d never even hung out alone, always with our husbands in tow, so I remember being a little nervous the first appointment she went with me to. Would I have anything to talk about with her? Would it be awkward? It wasn’t. She was still just as awesome, and I pretty much immediately asked her to be my bridesmaid.</p>\n<p>After that we just became closer, sharing the silliest stories, lots of wedding planning, a trip to <a title=\"New Orleans!\" href=\"/new-orleans/\">New Orleans</a>, and entirely too much food. It’s how we plan our evenings out… around what we want to eat. She’s one of my favorite people to talk to, and I hope that her absence in the city just forces us to chat more. I already promised her care packages and ridiculous cards in the mail, and I will start prepping them soon!</p>\n<p>I better stop now, or I’ll get too mushy for my own good! I’ll miss you, Tasha!!! <3 Sorry if you hate any of these photos- going through my albums, I realized I don’t have a whole lot of us together! We’ll have to fix that. 😉</p>\n<p>Has someone you loved ever moved away? What did you do to stay in touch?</p>\n",
  "featuredImage": {
    "src": "/posts/wordless-wednesday-best-friends/featured.png",
    "width": 663,
    "height": 250,
    "alt": "Wordless Wednesday: Best Friends on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1,
      "name": "Hodgepodge",
      "slug": "hodgepodge"
    }
  ],
  "tags": [
    {
      "id": 1196,
      "name": "best friends",
      "slug": "best-friends"
    },
    {
      "id": 1197,
      "name": "friendship",
      "slug": "friendship"
    },
    {
      "id": 1002,
      "name": "moving",
      "slug": "moving"
    },
    {
      "id": 1050,
      "name": "wordless wednesday",
      "slug": "wordless-wednesday"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/sunday-lazy-sunday/post.json
{
  "title": "Sunday, Lazy Sunday!",
  "slug": "sunday-lazy-sunday",
  "date": "20140720",
  "publishedDate": "2014-07-20",
  "excerpt": "<p>Our normal “Sunday Funday” will be a “MONDAY Funday” tomorrow instead, as Katie Crafts has been having technically difficulties all day and the post couldn’t get finished… and now it’s super late and I’m too tired! Haha! Enjoy these pics of our kitties and the kitties we are sitting for right now instead! Happy Sunday! [&hellip;]</p>\n",
  "content": "<p>Our normal “Sunday Funday” will be a “MONDAY Funday” tomorrow instead, as Katie Crafts has been having technically difficulties all day and the post couldn’t get finished… and now it’s super late and I’m too tired! Haha! Enjoy these pics of our kitties and the kitties we are sitting for right now instead! Happy Sunday!</p>\n<p><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-3660 post__image\" src=\"/posts/sunday-lazy-sunday/img-4562-1.jpg\" alt=\"Sunday, Lazy Sunday on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"457\">  <img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-3658 post__image\" src=\"/posts/sunday-lazy-sunday/img-4265-2.jpg\" alt=\"Sunday, Lazy Sunday on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"1173\"></p>\n<p><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-3657 post__image\" src=\"/posts/sunday-lazy-sunday/img-4190-3.jpg\" alt=\"Sunday, Lazy Sunday on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"994\"></p>\n",
  "featuredImage": {
    "src": "/posts/sunday-lazy-sunday/featured.jpg",
    "width": 1280,
    "height": 1396,
    "alt": "Sunday, Lazy Sunday on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 370,
      "name": "kitty",
      "slug": "kitty"
    },
    {
      "id": 37,
      "name": "loves cats",
      "slug": "loves-cats-2"
    },
    {
      "id": 46,
      "name": "lucky",
      "slug": "lucky"
    },
    {
      "id": 19,
      "name": "mabel",
      "slug": "mabel"
    },
    {
      "id": 790,
      "name": "marshal",
      "slug": "marshal"
    },
    {
      "id": 791,
      "name": "samantha",
      "slug": "samantha"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/taco-tuesday-5-recipes/post.json
{
  "title": "Taco Tuesday: 5 Recipes!",
  "slug": "taco-tuesday-5-recipes",
  "date": "20140909",
  "publishedDate": "2014-09-09",
  "excerpt": "<p>Taco Tuesday: 5 Recipes! (+ Bonus Burrito Recipe!) It’s Taco Tuesday! To celebrate, I spent many hours slaving away on Pinterest (read: 30 minutes enjoying Pinterest) to find you 5 taco recipes that make me drool! I also threw in a burrito recipe for Husband, because those are his favorite. I haven’t tried any of [&hellip;]</p>\n",
  "content": "<p><strong>Taco Tuesday: 5 Recipes! (+ Bonus Burrito Recipe!)</strong></p>\n<p>It’s Taco Tuesday! To celebrate, I spent many hours slaving away on Pinterest <em>(read: 30 minutes enjoying Pinterest)</em> to find you 5 taco recipes that make me drool! I also threw in a burrito recipe for Husband, because those are his favorite. I haven’t tried any of these yet, but certainly will once we move in to the new place and unearth our cookware!</p>\n<h2 style=\"text-align: center\"></h2>\n<h2 style=\"text-align: center\">#1. BBQ Tilapia and Sweet Potato Tacos</h2>\n<p style=\"text-align: center\">I’m not usually a fish person, unless it’s a very mild white fish like flounder or tilapia! And having it smothered in BBQ sauce and paired with sweet potatoes certainly helps! This recipe from <a title=\"Lemons and Basil BBQ Tilapia and Sweet Potato Taco Recipe\" href=\"http://lemonsandbasil.com/bbq-tilapia-and-sweet-potato-tacos/\" target=\"_blank\" rel=\"noopener noreferrer\">Lemons and Basil</a> is mouth watering. Where we are moving is two and a half blocks from the Italian Market, where I’ll be able to buy fresh produce, meat and fish whenever I please. I will definitely be trying this recipe out as soon as possible!</p>\n\n<h2 style=\"text-align: center\"> #2. Spicy Chicken Tacos With Corn, Feta and Avacado</h2>\n<p style=\"text-align: center\">I’m not really in to Feta cheese too much, so I may sub in something else, but overall this taco sounds pretty awesome! The recipe is from <a title=\"Serious Eats Spicy Chicken Taco\" href=\"http://www.seriouseats.com/recipes/2014/07/spicy-chicken-tacos-recipe.html\" target=\"_blank\" rel=\"noopener noreferrer\">Serious Eats</a> via Yasmin Fahr and they only take 20 minutes to make! I love spicy chicken and so does Husband, so I have a feeling this will be one we keep going back to.</p>\n\n<h2 style=\"text-align: center\"> #3. Korean BBQ Short Rib Tacos</h2>\n<p style=\"text-align: center\">Mmm. Just thinking about them makes me dizzy. Korean BBQ short rib tacos are one of my favoritest things on the whole entire planet. They are involved, and the ingredients list is far too long for something I will inhale in 45 seconds flat, but for those of you who want the challenge, here is a recipe from <a title=\"Korean BBQ Tacos on Lady and Pups\" href=\"http://www.ladyandpups.com/2012/11/21/chasing-kogi-truck-eng/\" target=\"_blank\" rel=\"noopener noreferrer\">Lady and Pups</a> that looks incredible.</p>\n<p><a href=\"http://www.ladyandpups.com/2012/11/21/chasing-kogi-truck-eng/\" target=\"_blank\" rel=\"noopener noreferrer\"><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-4246 post__image\" src=\"/posts/taco-tuesday-5-recipes/korean-taco-31-1024x681-1.jpg\" alt=\"Taco Tuesday: 5 Recipes on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"440\"></a></p>\n<h2 style=\"text-align: center\"> #4. Taco Pizza</h2>\n<p style=\"text-align: center\">If traditional tacos aren’t your thing, or you really want a spin on the old classic, a taco pizza is definitely a fun route to go! I love the recipe from <a title=\"Taste of Home Taco Pizza\" href=\"http://www.tasteofhome.com/recipes/taco-pizza\" target=\"_blank\" rel=\"noopener noreferrer\">Taste of Home</a>!</p>\n<p style=\"text-align: center\"><a href=\"http://www.tasteofhome.com/recipes/taco-pizza\" target=\"_blank\" rel=\"noopener noreferrer\"><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-full wp-image-4245 post__image\" src=\"/posts/taco-tuesday-5-recipes/exps1847-th0401c39d-2.jpg\" alt=\"Taco Tuesday: 5 Recipes on Katie Crafts; http://www.katiecrafts.com\" width=\"300\" height=\"300\"></a></p>\n<h2 style=\"text-align: center\"> #5. Layered Chopped Taco Salad</h2>\n<p style=\"text-align: center\"><a title=\"Foodie With Family Layered Chopped Taco Salad\" href=\"http://www.foodiewithfamily.com/2014/07/10/layered-chopped-taco-salad/\" target=\"_blank\" rel=\"noopener noreferrer\">Foodie With Family</a> is responsible for this deconstructed taco recipe, and it looks great! I love the idea of individual little bowls of salad using all taco ingredients. It looks way better than any taco salad I’ve received in a restaurant! Plus there are FRITOS on top! Anyway, salads are healthy… 😉</p>\n<h2 style=\"text-align: center\"><a href=\"http://www.foodiewithfamily.com/2014/07/10/layered-chopped-taco-salad/\" target=\"_blank\" rel=\"noopener noreferrer\"><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-full wp-image-4244 post__image\" src=\"/posts/taco-tuesday-5-recipes/layered-chopped-taco-salad-3.jpg\" alt=\"Taco Tuesday: 5 Recipes on Katie Crafts; http://www.katiecrafts.com\" width=\"450\" height=\"675\"></a></h2>\n<h2 style=\"text-align: center\"></h2>\n\n<h2 style=\"text-align: center\">BURRITO BONUS: Neato Frito Over-stuffed Burrito</h2>\n<p style=\"text-align: center\">Husband actually found this one all on his own. It also hails from <a title=\"Neato Frito Over-stuffed Burrito on Foodie With Family\" href=\"http://www.foodiewithfamily.com/2014/02/11/neato-frito-overstuffed-burritos/\" target=\"_blank\" rel=\"noopener noreferrer\">Foodie With Family</a> (have you checked the site out yet? There are so many good recipes!) and I have to say, it looks disgustingly delicious (and I don’t usually go for burritos!) I mean, pulled pork…cheeses…guac…more Fritos… how can I say no? Just look at it. LOOK!</p>\n<p><a href=\"http://www.foodiewithfamily.com/2014/02/11/neato-frito-overstuffed-burritos/\" target=\"_blank\" rel=\"noopener noreferrer\"><img loading=\"lazy\" decoding=\"async\" class=\"aligncenter size-medium wp-image-4241 post__image\" src=\"/posts/taco-tuesday-5-recipes/neato-frito-overstuffed-burritos-4.jpg\" alt=\"Taco Tuesday: 5 Recipes on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"442\"></a></p>\n<p>All of these recipes (at least, the ones in shells) require soft taco shells, but I always opt for hard ones if I can- the crunch is my favorite part of a taco! Now that I’m starving, I’m going to leave you to your taco dreams. Enjoy!</p>\n<p>Which of these recipes is your fave?</p>\n",
  "featuredImage": {
    "src": "/posts/taco-tuesday-5-recipes/featured.png",
    "width": 663,
    "height": 250,
    "alt": "Taco Tuesday: 5 Recipes on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 7,
      "name": "Cooks",
      "slug": "cooks"
    }
  ],
  "tags": [
    {
      "id": 1034,
      "name": "burrito",
      "slug": "burrito"
    },
    {
      "id": 1039,
      "name": "foodie with family",
      "slug": "foodie-with-family"
    },
    {
      "id": 1035,
      "name": "frito",
      "slug": "frito"
    },
    {
      "id": 1043,
      "name": "korean bbq taco",
      "slug": "korean-bbq-taco"
    },
    {
      "id": 1042,
      "name": "lady and pups",
      "slug": "lady-and-pups"
    },
    {
      "id": 1038,
      "name": "lemon and basil",
      "slug": "lemon-and-basil"
    },
    {
      "id": 954,
      "name": "recipes",
      "slug": "recipes"
    },
    {
      "id": 1040,
      "name": "serious eats",
      "slug": "serious-eats"
    },
    {
      "id": 1045,
      "name": "spicy chicken",
      "slug": "spicy-chicken"
    },
    {
      "id": 1037,
      "name": "sweet potato",
      "slug": "sweet-potato"
    },
    {
      "id": 1044,
      "name": "taco salad",
      "slug": "taco-salad"
    },
    {
      "id": 1033,
      "name": "taco tuesday",
      "slug": "taco-tuesday"
    },
    {
      "id": 1041,
      "name": "taste of home",
      "slug": "taste-of-home"
    },
    {
      "id": 1036,
      "name": "tilapia",
      "slug": "tilapia"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/heart-pillow-with-pocket-tutorial/post.json
{
  "title": "Heart Pillow with Pocket Tutorial",
  "slug": "heart-pillow-with-pocket-tutorial",
  "date": "20150113",
  "publishedDate": "2015-01-13",
  "excerpt": "<p>Project: Heart Pillow with Pocket Tutorial It’s the second week of January, so naturally it’s time to start our Valentine’s Day projects! This little sewing project is a quick work up, and perfect for any beginner- even your crafty kid! Use it to deliver a sweet little note to your Valentine, or perhaps a few [&hellip;]</p>\n",
  "content": "<p><strong>Project: Heart Pillow with Pocket Tutorial</strong></p>\n<p>It’s the second week of January, so naturally it’s time to start our <em>Valentine’s Day</em> projects! This little sewing project is a quick work up, and perfect for any beginner- even your crafty kid! Use it to deliver a sweet little note to your Valentine, or perhaps a few treats for your loved one!</p>\n<h2>Materials:</h2>\n<ul>\n<li>Sheet of paper + pencil</li>\n<li>Sewing machine</li>\n<li>Coordinating thread & needle</li>\n<li>Fabric in desired pattern and size</li>\n<li><a title=\"Poly-Fil\" href=\"http://amzn.to/1sdaUiy\" target=\"_blank\" rel=\"noopener noreferrer\">Poly-Fil</a> / stuffing</li>\n<li>Scissors</li>\n<li>Pins</li>\n</ul>\n<h2>Instructions:</h2>\n<ul>\n<li>Using the wonderful skills you learned in Kindergarten, fold your sheet of paper in half and trace half a heart. Cut it out with your scissors. This is now your pattern. If you hate it, trim away until you are happy with it’s size and shape. Remember, when you sew it together later, it will transform shape a little, so don’t be surprised when it doesn’t turn out looking EXACTLY as your paper heart does!</li>\n<li>Pin your new heart pattern to your fabric and cut out three hearts.</li>\n<li>Of these three, one will be the front of your pillow, one will be the back of your pillow, and one will be the pocket of your pillow. If your fabric is patterned, you may want to take a look at what each piece looks like and decide which you want to use for each area.</li>\n<li>Using whichever piece you choose to be your pocket, you will cut the top off of that heart to make a triangle. Don’t cut it down too small, or your pocket will be super tiny on the bottom of your heart!</li>\n<li>Fold over the edge you just cut about a half inch and pin. Sew across to make a small hem. I used a zig zag stitch to make it a little cuter! Leave the other two sides alone.</li>\n<li>Lay the pocket right side <em>up</em> on top of the piece you chose for your front (also right side up) so that it looks just how you want the finished product to be.</li>\n<li>Lay the back heart fabric piece right side <em>down </em>on top of the other two pieces, enveloping the pocket. Make sure all edges are matched up and pin all the way around.</li>\n<li>Use a straight stitch all the way around the heart to sew together all three pieces, leaving a small opening somewhere on the pillow for turning. I left my opening on the top to make it easier.</li>\n<li>Use scissors to trim excess, or pinking shears if you have them. Turn inside out through hole.</li>\n<li>Now that your pillow is completely adorable, you just need to stuff it! Fill it with poly-fil until it’s the firmness you desire, remembering to leave a little room near the hole for easier sewing.</li>\n<li>Use matching thread and a needle to hand stitch the opening closed, and you have yourself a Valentine pillow.</li>\n</ul>\n Pillow Front\n Pillow Back\n<p>Write a love note, slip it in the pocket, and leave it for your Husband to find! When Valentine’s Day is over, reuse the pillow for the Tooth Fairy for your kids! Such a cute little decoration, takes no time at all to make, and can be made in any size you desire. Happy crafting!</p>\n",
  "featuredImage": {
    "src": "/posts/heart-pillow-with-pocket-tutorial/featured.png",
    "width": 663,
    "height": 250,
    "alt": "Heart Pillow with Pocket Tutorial for Valentine's Day by Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 53,
      "name": "beginner",
      "slug": "beginner"
    },
    {
      "id": 17,
      "name": "heart",
      "slug": "heart"
    },
    {
      "id": 132,
      "name": "kids",
      "slug": "kids"
    },
    {
      "id": 55,
      "name": "pillow",
      "slug": "pillow"
    },
    {
      "id": 1154,
      "name": "pocket",
      "slug": "pocket"
    },
    {
      "id": 13,
      "name": "sewing",
      "slug": "sewing"
    },
    {
      "id": 14,
      "name": "valentine's day",
      "slug": "valentines-day"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/10-free-bag-tutorials/post.json
{
  "title": "10 Free Bag Tutorials",
  "slug": "10-free-bag-tutorials",
  "date": "20150129",
  "publishedDate": "2015-01-29",
  "excerpt": "<p>I love finding blog posts that host a whole array of free patterns all together in one list, so I figured, “Why not do that myself?” One of the very first things I ever tried to sew was a reversible tote bag, and it’s still one of my favorite ones to date. Here are even [&hellip;]</p>\n",
  "content": "<p>I love finding blog posts that host a whole array of free patterns all together in one list, so I figured, <em>“Why not do that myself?” </em>One of the very first things I ever tried to sew was a reversible tote bag, and it’s still one of my favorite ones to date. Here are even more great bag patterns so that you have your pick at bunch!</p>\n<p>I scoured the webs and found these wonderful blogs with free bag tutorials for their readers. I can’t wait to try each of these tutorials out, because who can have too many bags?! Be sure to check each of them out below!</p>\n<ol>\n<li><strong><a title=\"Reversible Tote Bag Tutorial by Katie Crafts\" href=\"/reversible-tote-bag-tutorial/\">Reversible Tote Bag Tutorial by Katie Crafts</a></strong></li>\n<li><strong><a title=\"Pleated Pouch Tutorial with Pattern by Lemon Squeezy Home\" href=\"http://lemonsqueezyhome.com/2010/10/pleated-pouch-tutorial-with-pattern.html\" target=\"_blank\" rel=\"noopener noreferrer\">Pleated Pouch Tutorial with Pattern by Lemon Squeezy Home</a></strong></li>\n<li><strong><a title=\"School Party Satchel by ikatbag\" href=\"http://www.ikatbag.com/2011/10/school-party-satchels.html\" target=\"_blank\" rel=\"noopener noreferrer\">School Party Satchel by ikatbag</a></strong></li>\n<li><strong><a title=\"Ruffle Zipper Pouch by See Kate Sew\" href=\"http://seekatesew.com/ruffle-zipper-pouch-with-geometric-stitching\" target=\"_blank\" rel=\"noopener noreferrer\">Ruffle Zip Pouches by See Kate Sew</a></strong></li>\n<li><strong><a title=\"Little Betty Bag by The Mother Huddle\" href=\"http://www.themotherhuddle.com/little-betty-bag-free-pattern-and-tutorial/\" target=\"_blank\" rel=\"noopener noreferrer\">Little Betty Bag by The Mother Huddle</a></strong></li>\n<li><strong><a title=\"Bucket Bag by Elvie Studio\" href=\"http://elviestudio.blogspot.com/2014/05/inspiration-monday_19.html?utm_source=feedburner&utm_medium=email&utm_campaign=Feed:+ElvieStudio+%28elvie+studio%29\" target=\"_blank\" rel=\"noopener noreferrer\">Bucket Bag by Elvie Studio</a></strong></li>\n<li><strong><a title=\"Fairly Bucket Bag by Sew Mama Sew\" href=\"http://www.sewmamasew.com/2014/09/fairly-bucket-bag-tutorial/\" target=\"_blank\" rel=\"noopener noreferrer\">Fairly Bucket Bag by Sew Mama Sew</a></strong></li>\n<li><strong><a title=\"Tohoku Tote by I Am Mamma Hear Me Roar\" href=\"http://www.iammommahearmeroar.net/2011/09/tohoku-tote.html\" target=\"_blank\" rel=\"noopener noreferrer\">The Tohoku Tote by I Am Momma Hear Me Roar</a></strong></li>\n<li><strong><a title=\"The Grandview Bag by The Boy Trifecta\" href=\"http://www.theboytrifecta.com/2010/10/grandview-bag-formerly-known-as-anthro.html\" target=\"_blank\" rel=\"noopener noreferrer\">The Grandview Bag by The Boy Trifecta</a></strong></li>\n<li><strong><a title=\"Buttercup Bag by Made By Rae\" href=\"http://www.made-by-rae.com/2009/02/free-buttercup-bag-sewing-pattern/\" target=\"_blank\" rel=\"noopener noreferrer\">Buttercup Bag by Made By Rae</a></strong></li>\n</ol>\n<p>What other patterns should I make lists of? Which is your fave bag?</p>\n",
  "featuredImage": {
    "src": "/posts/10-free-bag-tutorials/featured.png",
    "width": 663,
    "height": 250,
    "alt": "10 Free Bag Tutorials on Katie Crafts; http://www.katiecrafts.com"
  },
  "categories": [
    {
      "id": 1737,
      "name": "Crafts",
      "slug": "crafts"
    }
  ],
  "tags": [
    {
      "id": 1184,
      "name": "bags",
      "slug": "bags"
    },
    {
      "id": 185,
      "name": "diy",
      "slug": "diy"
    },
    {
      "id": 34,
      "name": "free",
      "slug": "free"
    },
    {
      "id": 33,
      "name": "pattern",
      "slug": "pattern"
    },
    {
      "id": 1187,
      "name": "pocket book",
      "slug": "pocket-book"
    },
    {
      "id": 1186,
      "name": "purse",
      "slug": "purse"
    },
    {
      "id": 13,
      "name": "sewing",
      "slug": "sewing"
    },
    {
      "id": 1185,
      "name": "tote",
      "slug": "tote"
    },
    {
      "id": 187,
      "name": "tutorial",
      "slug": "tutorial"
    }
  ]
}

=== seriouslysean/katiecrafts/data/posts/mabel-on-desk/post.json
{
  "title": "",
  "slug": "mabel-on-desk",
  "date": "20140804",
  "publishedDate": "2014-08-04",
  "excerpt": "<p><p>Put down laptop screen, see what is hiding behind it.</p></p>",
  "content": "<p><img class=\"size-medium post__image\" src=\"/posts/mabel-on-desk/img-4938.jpg\" alt=\"Mabel on Desk on Katie Crafts; http://www.katiecrafts.com\" width=\"663\" height=\"497\"></p><p>Put down laptop screen, see what is hiding behind it.</p>",
  "categories": [
    {
      "id": 9,
      "name": "Cats",
      "slug": "cats"
    }
  ],
  "tags": [
    {
      "id": 370,
      "name": "kitty",
      "slug": "kitty"
    },
    {
      "id": 37,
      "name": "loves cats",
      "slug": "loves-cats-2"
    },
    {
      "id": 19,
      "name": "mabel",
      "slug": "mabel"
    }
  ]
}
